// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { resolveSupabaseConfig } from './config';
import { supabaseSafeFetch } from './safeFetch';

const {
  url: SUPABASE_URL,
  publishableKey: SUPABASE_PUBLISHABLE_KEY,
  usedFallbackUrl,
  usedFallbackPublishableKey,
} = resolveSupabaseConfig(
  import.meta.env.VITE_SUPABASE_URL,
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY,
);

if (usedFallbackUrl || usedFallbackPublishableKey) {
  console.warn('Supabase env configuration was missing or invalid; using built-in fallback config.', {
    usedFallbackUrl,
    usedFallbackPublishableKey,
  });
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  global: {
    fetch: supabaseSafeFetch,
  },
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});